/* Admin */
const AP=[['overview','📊','Overview'],['products','📦','Products'],['edit','✏️','Add / Edit'],['orders','🧾','Orders'],['customers','👥','Customers'],['analytics','📈','Analytics'],['inventory','🏬','Inventory'],['coupons','🏷️','Coupons'],['reviews','⭐','Reviews'],['settings','⚙️','Settings']];
const sc=s=>({Delivered:'o',Shipped:'w',Pending:'w',Refunded:'r'}[s]||'o');
function editP(id){S.edit=id;go('admin/edit')}
function saveP(){const g=k=>$('#f_'+k).value,n=g('n').trim();if(!n||!(+g('p')>0))return toast('Name and a valid price are required');const o={name:n,cat:g('c'),price:+g('p'),old:+g('p')*1.2|0,stock:+g('s')};if(S.edit!=null){Object.assign(P[S.edit],o)}else P.push({id:P.length,rate:4.5,rev:0,e:'📦',h:Math.random()*360|0,sales:0,status:'Active',...o});toast('Product saved ✓');S.edit=null;go('admin/products')}
function Admin(pg){const M=window.M={
overview:()=>`<div class="kp">${[['Revenue','$38.9k','+23.9%'],['Orders','452','+21.8%'],['Customers','1,290','+12.4%'],['Products',P.length,'+2 new']].map((k,i)=>`<div class="card reveal" style="--i:${i}"><small style="color:var(--mut)">${k[0]}</small><b>${k[1]}</b><span class="up">▲ ${k[2]}</span></div>`).join('')}</div><div class="two"><div class="card"><h3>Revenue (k$)</h3>${Line(REVD,MO)}</div><div class="card"><h3>Top sellers</h3>${[...P].sort((a,b)=>b.sales-a.sales).slice(0,5).map(p=>`<div style="margin:10px 0"><div class="row" style="border:0;padding:0"><span>${p.e} ${p.name}</span><b>${p.sales}</b></div><div class="bar"><i style="width:${p.sales/10}%"></i></div></div>`).join('')}</div></div><div class="two"><div class="card"><h3 style="margin-bottom:8px">Recent orders</h3>${Table(['Order','Customer','Total','Status'],ORD.slice(0,5).map(o=>[o.id,o.c,money(o.t),Badge(o.s,sc(o.s))]))}</div><div class="card"><h3>Customer activity</h3>${NAMES.slice(0,5).map((n,i)=>`<div class="row"><span>${n}</span><small style="color:var(--mut)">${['placed an order','left a review','signed up','added to cart','used SAVE10'][i]}</small></div>`).join('')}</div></div>`,
products:()=>`<div class="tb" style="margin-bottom:12px">${Btn('+ Add product',"S.edit=null;go('admin/edit')")}</div><div class="card" style="padding:12px">${Table(['','Product','Category','Price','Stock','Status',''],P.map(p=>[p.e,p.name,p.cat,money(p.price),p.stock,Badge(p.stock?p.status:'Out','o'),`<button class="btn g s" onclick="editP(${p.id})">Edit</button> <button class="btn d s" onclick="confirmD('Delete ${p.name}?',()=>{P.splice(${p.id},1);P.forEach((x,i)=>x.id=i);toast('Deleted');route(1)})">Delete</button>`]))}</div>`,
edit:()=>{const p=S.edit!=null?P[S.edit]:{name:'',cat:'Audio',price:'',stock:''};return `<div class="card" style="padding:24px;max-width:640px"><h3 style="margin-bottom:14px">${S.edit!=null?'Edit':'Add'} product</h3><div class="fg"><label class="f">Name<input id="f_n" value="${p.name}"></label><label>Category<select id="f_c">${CATS.slice(1).map(c=>`<option ${p.cat===c?'selected':''}>${c}</option>`).join('')}</select></label><label>Price ($)<input id="f_p" type="number" value="${p.price}"></label><label>Stock<input id="f_s" type="number" value="${p.stock}"></label></div><div class="tb" style="margin-top:18px">${Btn('Save','saveP()')}${Btn('Cancel',"go('admin/products')",'g')}</div></div>`},
orders:()=>`<div class="card" style="padding:12px">${Table(['Order','Customer','Date','Total','Status'],ORD.map(o=>[o.id,o.c,o.d,money(o.t),Badge(o.s,sc(o.s))]))}</div>`,
customers:()=>`<div class="card" style="padding:12px">${Table(['Customer','Email','Orders','Spent'],NAMES.map((n,i)=>[`<b>${ini(n)}</b> ${n}`,n.toLowerCase().replace(' ','.')+'@mail.com',i+2,money(ORD[i].t*(i+2))]))}</div>`,
analytics:()=>`<div class="two"><div class="card"><h3>Monthly sales</h3>${Bars(REVD,MO)}</div><div class="card"><h3>Customers</h3>${Line(CUSD,MO,'#ff6b8b')}</div></div><div class="two"><div class="card"><h3>Orders</h3>${Bars(ORDD,MO,'#ff6b8b')}</div><div class="card"><h3>Product performance</h3>${P.slice(0,6).map(p=>`<div style="margin:10px 0"><small>${p.name}</small><div class="bar"><i style="width:${p.sales/10}%"></i></div></div>`).join('')}</div></div>`,
inventory:()=>`<div class="card" style="padding:12px">${Table(['Product','Stock','Level'],P.map(p=>[p.name,p.stock+(p.stock<10?' '+Badge('Low','r'):''),`<div class="bar" style="width:140px"><i style="width:${Math.min(100,p.stock)}%;background:${p.stock<10?'#e5484d':'var(--ac)'}"></i></div>`]))}</div>`,
coupons:()=>`<div class="tb" style="margin-bottom:12px"><input id="nc" placeholder="NEWCODE" aria-label="New coupon">${Btn('Create',"let v=$('#nc').value.trim().toUpperCase();v?(COUP.push({c:v,d:'Custom',u:0,on:1}),toast('Coupon created'),route(1)):toast('Enter a code')")}</div><div class="card" style="padding:12px">${Table(['Code','Type','Used','Active'],COUP.map((c,i)=>[`<b>${c.c}</b>`,c.d,c.u,`<button class="tg ${c.on?'on':''}" aria-label="Toggle" onclick="COUP[${i}].on^=1;route(1)"></button>`]))}</div>`,
reviews:()=>`<div class="card" style="padding:12px">${Table(['Product','Reviewer','Rating','Comment','Status',''],RVW.map((r,i)=>[r.p,r[0],'<span class="st">'+stars(r[1])+'</span>',r[2],Badge(r.ok?'Approved':'Pending',r.ok?'o':'w'),`<button class="btn g s" onclick="RVW[${i}].ok^=1;route(1)">${r.ok?'Hide':'Approve'}</button>`]))}</div>`,
settings:()=>`<div class="card" style="padding:20px;max-width:640px"><div class="row"><span>Store name</span><input value="LUMA" aria-label="Store name"></div>${[['Email order alerts',1],['Low-stock warnings',1],['Marketing emails',0]].map((s,i)=>`<div class="row"><span>${s[0]}</span><button class="tg ${s[1]?'on':''}" aria-label="${s[0]}" onclick="this.classList.toggle('on')"></button></div>`).join('')}<div class="row"><span>Dark mode</span><button class="btn g s" onclick="theme()">Toggle</button></div><br>${Btn('Save settings',"toast('Settings saved')")}</div>`};
return `<div class="adm"><aside class="sb" id="sb"><div class="logo" style="margin:4px 12px 20px" onclick="go('')">LUMA <small style="-webkit-text-fill-color:var(--mut);font-size:11px">ADMIN</small></div>${AP.map(a=>`<a class="${a[0]===pg?'a':''}" onclick="go('admin/${a[0]}')" tabindex="0">${a[1]} ${a[2]}</a>`).join('')}</aside><section class="main"><div class="top"><div class="tb"><button class="ib burger" aria-label="Menu" onclick="$('#sb').classList.toggle('o')">☰</button><h2>${(AP.find(a=>a[0]===pg)||[0,0,'Overview'])[2]}</h2></div><div class="tb" style="position:relative"><button class="ib" aria-label="Notifications" onclick="$('#nd').classList.toggle('o');S.notif=0;this.querySelector('.cnt')&&this.querySelector('.cnt').remove()">🔔${S.notif?'<span class="cnt">3</span>':''}</button><div class="dd" id="nd" style="top:44px"><div>🧾 New order #4827</div><div>⚠️ Flux Yoga Mat low on stock</div><div>⭐ New 5★ review</div></div><button class="ib" aria-label="Theme" onclick="theme()">🌓</button>${Btn('View store',"go('')",'g s')}</div></div><div class="view">${(M[pg]||M.overview)()}</div></section></div>`}
