/* Cart */
function add(id,q=1){const l=S.cart.find(x=>x.id===id&&x.k===(S.sel.k||''));const k=S.sel.k||'';l?l.q+=q:S.cart.push({id,q,k});toast('Added to cart 🛒');cartUI()}
function wish(id){S.wish.has(id)?S.wish.delete(id):S.wish.add(id);toast(S.wish.has(id)?'Saved to wishlist ♥':'Removed from wishlist');route(1)}
function totals(){const sub=S.cart.reduce((a,l)=>a+P[l.id].price*l.q,0),c=S.coupon,dc=c==='SAVE10'?sub*.1:c==='WELCOME20'?sub*.2:0,sh=!sub||sub>100||c==='FREESHIP'?0:9;return{sub,dc,sh,tot:sub-dc+sh}}
function qty(i,d){const l=S.cart[i];l.q+=d;if(l.q<1)return rm(i);cartUI()}
function rm(i){const el=document.querySelectorAll('.ci')[i];el&&el.classList.add('out');setTimeout(()=>{S.cart.splice(i,1);cartUI()},300)}
function coupon(){const v=$('#cp').value.trim().toUpperCase();COUP.find(c=>c.c===v&&c.on)?(S.coupon=v,toast('Coupon applied 🎉')):toast('Invalid or expired coupon');cartUI()}
function drawer(o){$('#dr').classList.toggle('o',!!o);if(o)cartUI()}
function cartUI(){const t=totals(),d=$('#dr');d.innerHTML=`<header><h3>Your cart (${S.cart.length})</h3><button class="ib" aria-label="Close" onclick="drawer(0)">✕</button></header><div class="body">${S.cart.length?S.cart.map((l,i)=>{const p=P[l.id];return `<div class="ci"><div class="th" style="--h:${p.h}">${p.e}</div><div style="flex:1"><b>${p.name}</b><br><small style="color:var(--mut)">${l.k||'Standard'}</small><br><div class="qt"><button aria-label="Less" onclick="qty(${i},-1)">−</button><span style="min-width:22px;text-align:center">${l.q}</span><button aria-label="More" onclick="qty(${i},1)">+</button></div></div><b>${money(p.price*l.q)}</b></div>`}).join(''):`<div class="emp"><b>🛍️</b>Your cart is empty.<br><br>${Btn('Start shopping',"drawer(0);go('')")}</div>`}</div>${S.cart.length?`<footer><div class="tb" style="margin-bottom:12px"><input id="cp" placeholder="Coupon (try SAVE10)" style="flex:1" aria-label="Coupon">${Btn('Apply','coupon()','g')}</div><div class="row"><span>Subtotal</span>${money(t.sub)}</div>${t.dc?`<div class="row"><span>Discount</span>−${money(t.dc)}</div>`:''}<div class="row"><span>Shipping</span>${t.sh?money(t.sh):'Free'}</div><div class="row"><b>Total</b><b>${money(t.tot)}</b></div><br>${Btn('Checkout →',"drawer(0);go('checkout')",'')}</footer>`:''}`;const n=$('#cc');if(n)n.textContent=S.cart.reduce((a,l)=>a+l.q,0)}
