/* Components */
const Btn=(l,f,c='')=>`<button class="btn ${c}" onclick="${f}">${l}</button>`;
const Badge=(t,c='o')=>`<span class="badge ${c}">${t}</span>`;
const Card=(p,i=0)=>`<article class="card pc reveal" style="--i:${i%6}"><div class="img" style="--h:${p.h}" onclick="go('product/${p.id}')" role="link" tabindex="0" onkeydown="if(event.key==='Enter')go('product/${p.id}')">${disc(p)?`<span class="badge">-${disc(p)}%</span>`:''}<button class="wl ${S.wish.has(p.id)?'on':''}" aria-label="Wishlist" onclick="event.stopPropagation();wish(${p.id})">${S.wish.has(p.id)?'♥':'♡'}</button><span class="e">${p.e}</span></div><div class="pb"><h3>${p.name}</h3><div class="st">${stars(p.rate)} <small style="color:var(--mut)">(${p.rev})</small></div><div class="pr">${money(p.price)}${disc(p)?`<s>${money(p.old)}</s>`:''}</div><div class="pa">${Btn('Add',`add(${p.id})`)}${Btn('Quick view',`qv(${p.id})`,'g')}</div></div></article>`;
const Grid=l=>l.length?`<div class="grid">${l.map(Card).join('')}</div>`:`<div class="emp"><b>🔍</b>No products match your search.<br><br>${Btn('Clear filters',"S.q='';S.cat='All';route()",'g')}</div>`;
const Table=(h,rows)=>rows.length?`<div class="tw2"><table class="tbl"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="emp"><b>📭</b>Nothing here yet.</div>`;
function Line(d,l,col='var(--ac)'){const m=Math.max(...d),W=600,H=180,pts=d.map((v,i)=>[i*W/(d.length-1),H-8-v/m*(H-24)]),pa=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join('');return `<svg viewBox="0 0 ${W} ${H+20}" width="100%" role="img" aria-label="Line chart"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${col}" stop-opacity=".3"/><stop offset="1" stop-color="${col}" stop-opacity="0"/></linearGradient></defs><path d="${pa}L${W} ${H}L0 ${H}Z" fill="url(#g)"/><path class="ln" d="${pa}" fill="none" stroke="${col}" stroke-width="3" stroke-linecap="round"/>${pts.map((p,i)=>`<text x="${p[0]}" y="${H+16}" font-size="11" fill="var(--mut)" text-anchor="middle">${l[i]}</text>`).join('')}</svg>`}
function Bars(d,l,col='var(--ac)'){const m=Math.max(...d),w=600/d.length;return `<svg viewBox="0 0 600 200" width="100%" role="img" aria-label="Bar chart">${d.map((v,i)=>{const h=v/m*160;return `<g><rect class="bx" style="animation-delay:${i*50}ms" x="${i*w+6}" y="${180-h}" width="${w-12}" height="${h}" rx="6" fill="${col}"><title>${l[i]}: ${v}</title></rect><text x="${i*w+w/2}" y="196" font-size="11" fill="var(--mut)" text-anchor="middle">${l[i]}</text></g>`}).join('')}</svg>`}
const MO=['Apr','May','Jun','Jul','Aug','Sep'],REVD=[18.2,22.5,21.1,27.8,31.4,38.9],ORDD=[210,265,248,320,371,452],CUSD=[120,150,140,190,230,290];
