/* Product */
function qv(id){const p=P[id];openM(`<div class="pd" style="margin:0;gap:20px"><div class="img" style="--h:${p.h};border-radius:18px;cursor:default"><span class="e">${p.e}</span></div><div><h2>${p.name}</h2><div class="st">${stars(p.rate)}</div><p class="pr" style="margin:8px 0">${money(p.price)}</p><p style="color:var(--mut);margin-bottom:16px">Premium ${p.cat.toLowerCase()} essential with a 2-year warranty.</p><div class="tb">${Btn('Add to cart',`add(${id});closeM()`)}${Btn('Details',`closeM();go('product/${id}')`,'g')}</div></div></div>`)}
function zoom(e){const r=e.currentTarget.getBoundingClientRect(),s=e.currentTarget.querySelector('.e').style;s.transformOrigin=`${(e.clientX-r.left)/r.width*100}% ${(e.clientY-r.top)/r.height*100}%`;s.transform='scale(1.6)'}
function pick(t,v,el){S.sel[t]=v;el.parentNode.querySelectorAll('button').forEach(b=>b.classList.remove('a'));el.classList.add('a');S.sel.k=[S.sel.size,S.sel.color].filter(Boolean).join(' / ')}
function img(h,e){const g=$('#gi');g.style.opacity=0;setTimeout(()=>{g.style.setProperty('--h',h);g.querySelector('.e').textContent=e;g.style.opacity=1},150)}
function Product(id){const p=P[id];if(!p)return `${Nav()}<div class="emp view"><b>⚠️</b>Product not found.<br><br>${Btn('Back to shop',"go('')")}</div>`;S.recent=[id,...S.recent.filter(x=>x!==id)].slice(0,4);S.sel={size:'M',color:'Midnight',k:'M / Midnight'};const rel=P.filter(x=>x.cat===p.cat&&x.id!==id).concat(P.filter(x=>x.cat!==p.cat)).slice(0,4);
return `${Nav()}<main class="wrap view"><p style="margin-top:20px;color:var(--mut)"><a style="cursor:pointer" onclick="go('')">Shop</a> / ${p.cat} / ${p.name}</p><div class="pd"><div class="gal"><div class="img" id="gi" style="--h:${p.h};transition:opacity .15s" onmousemove="zoom(event)" onmouseleave="this.querySelector('.e').style.transform=''"><span class="e">${p.e}</span></div><div class="th2">${[0,40,80,120].map((o,i)=>`<button class="${i?'':'a'}" style="--h:${p.h+o}" aria-label="Image ${i+1}" onclick="img(${p.h+o},'${p.e}');this.parentNode.querySelectorAll('button').forEach(b=>b.classList.remove('a'));this.classList.add('a')">${p.e}</button>`).join('')}</div></div>
<div><div class="tb">${Badge(p.cat,'w')} ${p.stock<10?Badge('Only '+p.stock+' left','r'):Badge('In stock')}</div><h1 style="margin:12px 0">${p.name}</h1><div class="st">${stars(p.rate)} <small style="color:var(--mut)">${p.rate} · ${p.rev} reviews</small></div><p class="pr" style="font-size:32px;margin:12px 0">${money(p.price)}${disc(p)?`<s>${money(p.old)}</s> ${Badge('-'+disc(p)+'%')}`:''}</p><p style="color:var(--mut);margin-bottom:20px">Crafted with premium materials and finished by hand. Designed to last, backed by a 2-year warranty and 30-day free returns.</p><b>Size</b><div class="opt">${['S','M','L','XL'].map(s=>`<button class="${s==='M'?'a':''}" onclick="pick('size','${s}',this)">${s}</button>`).join('')}</div><b>Color</b><div class="opt">${[['Midnight','#14141f'],['Sand','#d9c3a0'],['Coral','#ff6b8b']].map((c,i)=>`<button class="sw ${i?'':'a'}" aria-label="${c[0]}" style="background:${c[1]}" onclick="pick('color','${c[0]}',this)"></button>`).join('')}</div><div class="tb"><div class="qt"><button onclick="let q=$('#pq');q.textContent=Math.max(1,+q.textContent-1)" aria-label="Less">−</button><span id="pq" style="min-width:26px;text-align:center">1</span><button onclick="let q=$('#pq');q.textContent=+q.textContent+1" aria-label="More">+</button></div>${Btn('Add to cart',`add(${id},+$('#pq').textContent)`)}${Btn('Buy now',`add(${id},+$('#pq').textContent);go('checkout')`,'g')}<button class="btn g" onclick="wish(${id})" aria-label="Wishlist">${S.wish.has(id)?'♥':'♡'}</button></div></div></div>
<section class="sec"><h2 style="margin-bottom:16px">Reviews</h2><div class="rv">${REV.map(r=>`<div class="card" style="padding:18px"><div class="st">${stars(r[1])}</div><p>${r[2]}</p><b>${r[0]}</b></div>`).join('')}</div></section>${Sec('Related products','YOU MAY ALSO LIKE',rel)}${S.recent.length>1?Sec('Recently viewed','HISTORY',S.recent.filter(x=>x!==id).map(x=>P[x])):''}</main>`}
