/* Store */
function Nav(){return `<nav class="nav"><div class="wrap"><button class="ib burger" aria-label="Menu" onclick="$('.links').style.display=$('.links').style.display==='flex'?'':'flex'">☰</button><span class="logo" onclick="go('')">luma<b class="dot">.</b></span><div class="links" style="flex-direction:column"><a onclick="go('')">Shop</a><a onclick="S.cat='Audio';go('')">Audio</a><a onclick="S.cat='Home';go('')">Home</a><a onclick="go('admin/overview')">Admin</a></div><div class="srch"><input id="q" type="search" placeholder="Search products…" aria-label="Search" autocomplete="off" oninput="sug(this.value)" onkeydown="if(event.key==='Enter'){S.q=this.value;S.pg=1;go('');}"><div class="dd" id="sg"></div></div><button class="ib" aria-label="Toggle theme" onclick="theme()">🌓</button><button class="ib" aria-label="Wishlist">♡<span class="cnt">${S.wish.size}</span></button><button class="ib" aria-label="Open cart" onclick="drawer(1)">🛒<span class="cnt" id="cc">${S.cart.reduce((a,l)=>a+l.q,0)}</span></button></div></nav>`}
function sug(v){const m=v?P.filter(p=>p.name.toLowerCase().includes(v.toLowerCase())).slice(0,4):[],d=$('#sg');d.innerHTML=m.map(p=>`<div onclick="go('product/${p.id}')">${p.e} ${p.name}</div>`).join('');d.classList.toggle('o',m.length>0)}
function list(){let l=P.filter(p=>(S.cat==='All'||p.cat===S.cat)&&p.name.toLowerCase().includes(S.q.toLowerCase()));const f={pop:(a,b)=>b.sales-a.sales,lo:(a,b)=>a.price-b.price,hi:(a,b)=>b.price-a.price,rt:(a,b)=>b.rate-a.rate};return l.sort(f[S.sort])}
function Sec(t,s,l){return `<section class="sec"><div class="sh2"><div><small style="color:var(--ac);font-weight:700">${s}</small><h2>${t}</h2></div></div><div class="grid">${l.map(Card).join('')}</div></section>`}
function Store(){const l=list(),n=Math.ceil(l.length/6)||1,pg=Math.min(S.pg,n);return `${Nav()}<main class="wrap view"><section class="bento"><div class="b-main"><small class="eyebrow">AUTUMN COLLECTION 2026</small><h1>Sequoia inspiring music.</h1><p>Thoughtfully designed audio, wearables and home essentials. Up to 30% off, free shipping over $100.</p>${Btn('View all products →',"document.getElementById('shop').scrollIntoView()",'dark')}<div class="b-orb" aria-hidden="true">🎧</div></div><div class="b-side"><div class="b-card"><small>Popular colors</small><div class="dots"><i style="background:#2f5bff"></i><i style="background:#ff7a59"></i><i style="background:#22c55e"></i><i style="background:#facc15"></i><i style="background:#111"></i></div></div><div class="b-card t1" onclick="S.cat='Audio';S.pg=1;route(1)"><small>New gen</small><b>X-Bud earbuds</b><span>🎵</span></div><div class="b-card t2" onclick="S.cat='Wearables';S.pg=1;route(1)"><small>Light grey surface</small><b>Smart wearables</b><span>⌚</span></div></div></section>
${Sec('Featured','HANDPICKED',[...P].sort((a,b)=>b.rate-a.rate).slice(0,4))}
<section class="sec" id="shop"><div class="sh2"><h2>Shop all</h2><div class="tb"><select aria-label="Sort" onchange="S.sort=this.value;route(1)">${[['pop','Most popular'],['rt','Top rated'],['lo','Price: low → high'],['hi','Price: high → low']].map(o=>`<option value="${o[0]}" ${S.sort===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></div></div><div class="chips">${CATS.map(c=>`<button class="chip ${S.cat===c?'a':''}" onclick="S.cat='${c}';S.pg=1;route(1)">${c}</button>`).join('')}</div>${S.q?`<p style="margin-bottom:12px;color:var(--mut)">Results for “${S.q}”</p>`:''}${Grid(l.slice((pg-1)*6,pg*6))}<div class="pg">${Array.from({length:n},(_,i)=>`<button class="chip ${pg===i+1?'a':''}" onclick="S.pg=${i+1};route(1)">${i+1}</button>`).join('')}</div></section>
<section class="promo reveal"><div style="background:linear-gradient(135deg,#ff6b8b,#ff9d6b)"><h2>Save 10% today</h2><p style="margin:8px 0 16px">Use code SAVE10 at checkout.</p>${Btn('Shop now',"go('')",'g" style="color:#fff;border-color:#fff')}</div><div style="background:linear-gradient(135deg,#14141f,#3b2bd9)"><h2>Free shipping</h2><p style="margin:8px 0 16px">On every order over $100.</p></div></section>
${Sec('Trending now','🔥 HOT',[...P].sort((a,b)=>b.sales-a.sales).slice(0,4))}${Sec('New arrivals','JUST LANDED',P.slice(-4))}
<section class="sec"><div class="sh2"><h2>Loved by 20,000+ customers</h2></div><div class="rv">${REV.map((r,i)=>`<div class="card reveal" style="--i:${i}"><div class="st">${stars(r[1])}</div><p style="margin:8px 0">“${r[2]}”</p><b>${r[0]}</b></div>`).join('')}</div></section>
<section class="card news reveal"><h2>Get 10% off your first order</h2><p style="color:var(--mut)">Join the list for drops and private sales.</p><form onsubmit="event.preventDefault();this.email.value.includes('@')?(toast('Welcome aboard ✉️'),this.reset()):toast('Please enter a valid email')"><input name="email" placeholder="you@example.com" aria-label="Email" style="min-width:240px">${Btn('Subscribe','')}</form></section></main><footer><div class="wrap"><div><span class="logo">luma<b class="dot">.</b></span><p>Design-led essentials, delivered.</p></div><div>Shop · Journal · Support · Returns</div><div>© 2026 Luma Commerce</div></div></footer>`}
